# -*- mode: makefile; -*-

parse:
	python ../analysis/parse_outputs_snapshot_method_dependence.py save save

analysis:
	python ../analysis/pick_snapshots.py --csv
	python ../analysis/analysis_0qm_0mm.py
