# -*- mode: makefile; -*-

ANALYSIS_DIR=../analysis

parse:
	python ${ANALYSIS_DIR}/parse_outputs_snapshot_method_dependence_4fs.py save save

analysis:
	python ${ANALYSIS_DIR}/analysis_snapshot_method_dependence_fft.py
