# -*- mode: makefile; -*-

parse:
	python ../analysis/parse_outputs.py save save --parse-frequencies --parse-dipoles

analysis:
	# python ../analysis/plot_snapshots.py
	python ../analysis/analysis.py --do-condon-plots --do-snapshot-plots

stats:
	cd inputs_freq_1qm_random && python ../../analysis/stats.py
	cd inputs_freq_2qm_random && python ../../analysis/stats.py
	cd inputs_freq_3qm_random && python ../../analysis/stats.py
